services:
  zookeeper:
    build: ./container_images/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./config/zoo.cfg:/zookeeper/conf/zoo.cfg
    networks:
      - dahbest
  
  kafka:
    build: ./container_images/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./config/server.properties:/kafka/config/server.properties
      - ./kafka_data:/kafka/logs
    networks:
      - dahbest

networks:
  dahbest:
    driver: bridge
